name: Build & Push Docker Image (Node)

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/jr-smartbreath-ui   # ชื่อรูปบน Docker Hub
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (ออปชัน) รัน test ของ Node ก่อน build
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run tests (skip if no script)
        run: |
          if npm run -s | grep -q '^  test'; then
            npm test
          else
            echo "No test script. Skipping."
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build single-arch และโหลดเข้า local daemon
      - name: Build Docker Image (load to local)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile      # ปรับตามที่เก็บ Dockerfile (เช่น CI/Dockerfile)
          push: false                 # ยังไม่ push ตอนนี้
          load: true                  # สำคัญ: โหลดเข้า docker daemon สำหรับขั้นตอน push ถัดไป
          tags: ${{ env.DOCKER_IMAGE }}:latest
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push Docker Image(s)
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:latest

